### ISSUE TITLE
vendor/bin/jigsaw init blog

### ISSUE THREAD

**Issue by actuallyakash** [tightenco/jigsaw-blog-template#23]
After running this:
`vendor/bin/jigsaw init blog`
or 
`vendor/bin/jigsaw init docs`

It's showing this:
`The 'tightenco\jigsaw-blog-template' preset could not be found.`
and
`The 'tightenco\jigsaw-docs-template' preset could not be found.`

Am I doing something wrong?
Help.

**Comment by mattstauffer** [comment]
@actuallyakash That error will show up when the system tries to run

```php
composer require tightenco\jigsaw-blog-template
```

That *should* throw an error because the slash goes forward, not backward. But further, that should never *happen*, since, in our code, the slash goes the other way:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/151829/50389404-f0506480-06f7-11e9-9fb1-d67ffff892ba.png">

I'm wondering if there's something in the Process-running system treating that like a directory separator, and we'll need to add some enclosing quotes around that. Are you, by any chance, on Windows?

Thanks!

(If anyone else sees this later, I'm imagining maybe it's Symfony's Process file's prepareWindowsCommandLine method or something like it?)

**Comment by actuallyakash** [comment]
Yes, I'm using windows.
Is there any other config for windows users?

You're right, after running this cmd -
`vendor/bin/jigsaw init blog`

it's showing this-
```
> composer require tightenco\jigsaw-blog-template
The 'tightenco\jigsaw-blog-template' preset could not be found.
```

and by running this cmd-
` composer require tightenco/jigsaw-blog-template`
it's working. I just changed the **\** to **/**.

however, the blog template is not configured properly. Still figuring out.

**Comment by mattstauffer** [comment]
@actuallyakash I think we need to update the code so that Symfony doesn't try to switch the direction of that slash. It may be just wrapping the repo name in double quotes will do it? We're all back in the office today but working through a lot of issues (plus our day jobs) so we'll get to it as soon as we can :)

**Comment by damiani** [comment]
@actuallyakash I've fixed this in Jigsaw v1.3.1. If you update Jigsaw and try `jigsaw init blog` again, it should install correctly.

**Comment by actuallyakash** [comment]
@damiani oh, Great.
I'll give it a go.
Thank you.

**Comment by rehanvdm** [comment]
@damiani I am having the same issue, also on windows. I can see from the composer.lock file that tightenco/jigsaw is on v1.3.2 

Also that under /vendor/tightenco/ their is only jigsaw.

I can see that on @mattstauffer repo, that he has an extra require, the one you are talking about above(https://github.com/matopher/blog/blob/master/composer.json)

**Comment by rehanvdm** [comment]
Okay so I have added the extra require and then the command works. I am then presented with this output:

```It looks like you've already run 'jigsaw init' on this project.
Running it again will overwrite important files.

What would you like to do? (default a)
  [a] archive your existing site, then initialize a new one
  [d] delete your existing site, then initialize a new one
  [c] cancel
```
So is it even needed to run that command then? Seems it has already been run to generate this template.

**Comment by damiani** [comment]
@actuallyakash I just pushed another fix that should solve this once and for all. Can you test and confirm?

@rehanvdm There should only be one `require` (`tightenco/jigsaw`), the template repo will get installed when running the `init blog` command. The question it's asking you about archiving your existing site doesn't indicate that the command ran fully; it will ask you that whenever it finds a `config.php` file already in your project.

**Comment by actuallyakash** [comment]
@damiani Hey thankyou, I'll give it a try for sure. Sorry for the late reply. 😅 
Will post the status here after testing.

**Comment by begueradj** [comment]
Still the same issue today
