### ISSUE TITLE
could search pick up all pages?

### ISSUE THREAD

**Issue by diomed** [tightenco/jigsaw-blog-template#39]
I hoped search works for all pages, but when I look for content of About - there are no results.
how can I include more pages?

**Comment by atymic** [comment]
The issue is that the index is generated from the `front-matter` data in your markdown posts.

https://github.com/tightenco/jigsaw-blog-template/blob/master/listeners/GenerateIndex.php#L9-L18

I don't think jigsaw has blade pages as collections, so some other solution would be required to add them to the index.

**Comment by bakerkretzmar** [comment]
@diomed to index the full content of each page, you can update the listener linked above with something like this:

```diff
  'snippet' => $page->getExcerpt(),
+ 'content' => $page->getContent(),
```

Feel free to open another issue if you have other questions!
