### ISSUE TITLE
Default Category Page Possible?

### ISSUE THREAD

**Issue by vmitchell85** [tightenco/jigsaw-blog-template#40]
Would it be possible to add a default category page?

If I go to a category url I don't have or haven't created yet I get a `No input file specified` error.

See https://vincemitchell.me/blog/categories/jigsaw/

So, if I use a new category in my post I have to remember to create a file for that category.

Would it be possible to add capability for a "catch all" or `_default.md` file maybe?

Hope that makes sense.

**Comment by camuthig** [comment]
I put together an event listener that accomplishes this task for me. Instead of using a `_default.md`, it directly extends the `_layouts.category` layout and sets a default `title` on each item. So the page will have a title of `Category: <name of category>` and then the list of the relevant posts. 

I'm not sure if the way I accomplished this was the best route to take, essentially reloading all of the collections and configurations again after they were already loaded once, but it allows me to reuse the heavy lifting that Jigsaw is doing for me.

https://github.com/camuthig/jigsaw-blog-default-categories

Hope it helps. Open to suggestions as well.

**Comment by bakerkretzmar** [comment]
Somewhat related to tightenco/jigsaw#273.

**Comment by bakerkretzmar** [comment]
@vmitchell85 closing this for now as I think @camuthig's solution will work for you and this isn't currently possible with Jigsaw out of the box. We'll definitely keep this in mind for v2.
