### ISSUE TITLE
@push('meta') doesn't work correctly

### ISSUE THREAD

**Issue by stancl** [tightenco/jigsaw-blog-template#52]
Pushing `description` and `og:description` to the `meta` stack doesn't work the way it should -- since there is `<meta property="og:description" content="{{ $page->siteDescription }}" />` above, it takes precedence.

Also this should be fixed in the `master` layout:
```diff
-<meta name="description" content="{{ $page->meta_description ?? $page->siteDescription }}">
+<meta name="description" content="{{ $page->description ?? $page->siteDescription }}">
```

The `og:description` can be fixed by making this change to the master layout:
```diff
-<meta property="og:description" content="{{ $page->siteDescription }}" />
+<meta property="og:description" content="{{ $page->description ?? $page->siteDescription }}" />
```

And the `og:url` can be removed from the `post` layout, since it's the same in the `master` layout.

I can create a PR fixing this.

However, I'm not sure how the `og:type` should be overwritten:
master:
```html
<meta property="og:type" content="website" />
```
post:
```html
<meta property="og:type" content="article" />
```

The type should probably come from some `$page` property or method.

**Comment by damiani** [comment]
I think we should probably remove the `@push('meta')` sections from the pages that they're on now (since they're causing duplication, as you say), and just use page variables where necessary. So we can update the meta block in `master` to read:

```php
...
<meta name="description" content="{{ $page->description ?? $page->siteDescription }}">

<meta property="og:title" content="{{ $page->title ? $page->title . ' | ' : '' }}{{ $page->siteName }}"/>
<meta property="og:type" content="{{ $page->type ?? 'website' }}" />
<meta property="og:url" content="{{ $page->getUrl() }}"/>
<meta property="og:description" content="{{ $page->description ?? $page->siteDescription }}" />

...
```

...then, on top-level templates (like `about`, `blog`, `contact`), use variables to set descriptions where desired:

```php
---
description: A little bit about the site
---

@extends('_layouts.master')
...
```

In the case of `_layouts/post.blade.php`, though, we'd have to set `$page->type` in a `@php` block; that template is extended by the individual posts, so we can't add YAML front matter to it. But this would set `type` to `article` for all pages that extend `post.blade.php`:

```php
@extends('_layouts.master')

@php
    $page->type = 'article';
@endphp

...
```
